version: "3"

includes:
  verify: ./scripts/Taskfile-verify.yml
  deploy: ./scripts/Taskfile-deploy.yml
  destroy: ./scripts/Taskfile-destroy.yml

vars:
  PROJECT_NAME: "whopper"
  OPERATOR_CLUSTER_NAME: "operator-cluster"
  WHOPPER_CLUSTER_NAME: "whopper-cluster"
  OPERATOR_POD_NAME: "pulumi-kubernetes-operator"
  OPERATOR_CLUSTER_MACHINE_TYPE: "n1-standard-1"
  OPERATOR_CLUSTER_REGION: "europe-west3"
  CLUSTER_ZONE: "europe-west3-b"
  OPERATOR_CLUSTER_NODE_COUNT: 1
  GCP_PROJECT: "liquid-leonard-pahlke-302"
  GLOBAL_ENV:
    sh: echo $(git rev-parse --abbrev-ref HEAD)
  LOCAL_WHOPPER_KUBECONFIG_PATH:
    sh: echo $(pwd)'/.kube/whopper-config'
  LOCAL_OPERATOR_KUBECONFIG_PATH:
    sh: echo $(pwd)'/.kube/operator-config'
  GLOBAL_OPERATOR_INFRA_PATH:
    sh: echo $(pwd)'/operator-infra'
  GLOBAL_WHOPPER_INFRA_PATH:
    sh: echo $(pwd)'/whopper-infra'

tasks:
  kubectl-o:
    desc: kubectl wrapper to interact with operator cluster
    cmds:
      - kubectl {{.CLI_ARGS}} --kubeconfig {{.LOCAL_OPERATOR_KUBECONFIG_PATH}}
    sources:
      - "{{.LOCAL_OPERATOR_KUBECONFIG_PATH}}"

  kubectl-w:
    desc: kubectl wrapper to interact with the whopper cluster
    cmds:
      - kubectl {{.CLI_ARGS}} --kubeconfig {{.LOCAL_WHOPPER_KUBECONFIG_PATH}}
    sources:
      - "{{.LOCAL_WHOPPER_KUBECONFIG_PATH}}"

  init-project:
    cmds:
      - echo "Project initialization happens from main, after that features are be implemented and tested on other branches"
      - git checkout main
      - echo "Deploy operator cluster"
      - task: deploy:operator
      - echo "Set pulumi config to deploy whopper"
      - pulumi config set --secret pulumiAccessToken {{.PULUMI_ACCESS_TOKEN}} -C {{.GLOBAL_OPERATOR_INFRA_PATH}}
      - pulumi config set stackProjectRepo {{.PROJECT_REPO}} -C {{.GLOBAL_OPERATOR_INFRA_PATH}}
      - pulumi config set stackCommit {{.COMMIT_SHA}} -C {{.GLOBAL_OPERATOR_INFRA_PATH}}
      - pulumi config set stackName {{.PULUMI_ORG}}/{{.PULUMI_STACK_NAME}}/{{.ENV}} -C {{.GLOBAL_OPERATOR_INFRA_PATH}}
      - pulumi config set operatorPodName {{.OPERATOR_POD_NAME}}} -C {{.GLOBAL_OPERATOR_INFRA_PATH}}
      - pulumi config set --secret operatorKubeconfig $(cat {{.LOCAL_KUBECONFIG_PATH}}) -C {{.GLOBAL_OPERATOR_INFRA_PATH}}
      - echo "pulumi config set, deploy pulumi whopper project to cluster. The whopper on the main branch also deploys the pulumi kubernetes operator to the operator cluster"
      - task: deploy:whopper
      - echo "check if operator pods is running in the operator cluster"
      - task: kubectl-o -- get pods -o wide -l name={{.OPERATOR_POD_NAME}}
    vars:
      PULUMI_ORG: leonardpahlke
      PULUMI_ACCESS_TOKEN:
        sh: $PULUMI_ACCESS_TOKEN
      COMMIT_SHA:
        sh: git rev-parse HEAD
      PROJECT_REPO: "https://github.com/leonardpahlke/whopper"
      PULUMI_STACK_NAME: "whopper"

  operator-logs:
    cmds:
      - task: kubectl-o -- logs -l name={{.OPERATOR_POD_NAME}} -f
    sources:
      - "{{.LOCAL_OPERATOR_KUBECONFIG_PATH}}"
