env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  # import/no-unresolved: [2, {commonjs: true, amd: true}]
  'import/no-unresolved': 'off'
  'import/extensions': 'off'
  '@typescript-eslint/no-unused-vars': 'error'
  '@typescript-eslint/consistent-type-definitions':
    - error
    - type

