apiVersion: apps/v1
kind: Deployment
metadata:
  name: discoverer
  namespace: default
  labels:
    app: discoverer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discoverer
  template:
    metadata:
      labels:
        app: discoverer
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "discoverer"
        dapr.io/app-protocol: "grpc"
        dapr.io/app-port: "50051"
        dapr.io/config: "serverconfig"
    spec:
      containers:
      - name: discoverer
        image: quay.io/leonardpahlke/whopper-discoverer:latest
---