apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
    name: "discoverer"
    namespace: "default"
    labels:
        app: discoverer
spec:
    replicas: 1
    selector:
        matchLabels:
            app: discoverer
    template:
        metadata:
            labels:
                app: discoverer
            annotations:
                dapr.io/enabled: "true"
                dapr.io/app-id: "discoverer"
                dapr.io/app-protocol: "grpc"
                dapr.io/app-port: "50055"
                dapr.io/config: "tracing"
                dapr.io/log-level: "debug"
    tracing:
        samplingRate: "1"
        zipkin:
            endpointAddress: http://localhost:9411/api/v2/spans
    features:
        - name: proxy.grpc
          enabled: true
