on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.29

  # test:
  #   strategy:
  #     matrix:
  #       go-version: [1.17.x]
  #       platform: [ubuntu-latest, macos-latest, windows-latest]
  #   runs-on: ${{ matrix.platform }}
  #   steps:
  #     - name: Install Go
  #       if: success()
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: ${{ matrix.go-version }}
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Run tests
  #       run: go test -count=1 -cover -coverprofile coverage.out $(go list ./... )

  # coverage:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Install Go
  #       if: success()
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: 1.17
  #       id: go
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Calc coverage
  #       run: go test -v -covermode=count -coverprofile coverage.out $(go list ./... )
  #     - name: Convert coverage.out to coverage.lcov
  #       uses: jandelgado/gcov2lcov-action@v1.0.6
  #     - name: Coveralls
  #       uses: coverallsapp/github-action@v1.1.2
  #       with:
  #         github-token: ${{ secrets.github_token }}
  #         path-to-lcov: coverage.lcov