name: Typescript verify
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Set up Node 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install taskfile
        run: go install github.com/go-task/task/v3/cmd/task@latest

      - name: Install whopper node packages
        run: task verify:install-whopper-ts

      - name: Install operator node packages
        run: task verify:install-operator-ts

      - name: Verify typescript code
        run: task verify:ts
